name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"  # Se ejecuta todos los d√≠as a las 18:00 UTC
  workflow_dispatch:       # Permite ejecutarlo manualmente

permissions:
  contents: write          # Permite hacer commits en tu repo

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-3d-profile
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}   # Usa tu token personal
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git commit -m "generated 3D profile"; then
            git push
          fi
